# Generated by Django 3.2.4 on 2021-07-10 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brooklyn', '0009_auto_20210710_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default='', max_length=150)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(default='', max_length=200000)),
                ('remarks', models.CharField(default='', max_length=120000)),
                ('diagnosis', models.CharField(default='', max_length=300000)),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2021, 7, 10, 10, 2, 25, 436707, tzinfo=utc))),
                ('imageLink', models.CharField(default='', max_length=10000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brooklyn.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brooklyn.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
