# Generated by Django 3.2.4 on 2021-07-10 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brooklyn', '0010_auto_20210710_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 10, 14, 1, 949815, tzinfo=utc)),
        ),
    ]
